name: Simple Lichess Bot

on:
  workflow_dispatch:
    inputs:
      restart_reason:
        description: 'Reason for restart'
        required: false
        default: 'Manual start'
  schedule:
    - cron: '0 */2 * * *'  # Every 2 hours

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 115
    
    concurrency:
      group: simple-lichess-bot
      cancel-in-progress: true
    
    env:
      LICHESS_TOKEN: ${{ secrets.LICHESS_TOKEN }}
      BOT_NAME: ${{ secrets.BOT_NAME }}
      
    steps:
      - name: Checkout BotLi
        uses: actions/checkout@v4
        with:
          repository: 'Torom/BotLi'
          ref: 'main'
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir
          
      - name: Verify Installation
        run: |
          python -c "import chess, aiohttp, yaml; print('✅ All dependencies OK')"
          
      - name: Setup Engines
        run: |
          mkdir -p engines
          
          # Download Stockfish dev
          echo "📥 Downloading Stockfish development version..."
          curl -L -o stockfish.zip "https://abrok.eu/stockfish/latest/linux/stockfish_x64_modern.zip"
          unzip -o stockfish.zip -d engines/
          find engines/ -name "stockfish*" -type f -exec mv {} engines/stockfish_dev \;
          chmod +x engines/stockfish_dev
          
          # Download Stockfish 17
          echo "📥 Downloading Stockfish 17..."
          curl -L -o engines/stockfish_17 "https://github.com/official-stockfish/Stockfish/releases/download/sf_17/stockfish-ubuntu-x86-64-modern"
          chmod +x engines/stockfish_17
          
          # Make fairy-stockfish executable if exists
          if [ -f "engines/fairy-stockfish" ]; then
            chmod +x engines/fairy-stockfish
          fi
          
          # Verify engines work
          echo "🔧 Verifying engines..."
          ./engines/stockfish_dev --help || echo "Stockfish dev ready"
          ./engines/stockfish_17 --help || echo "Stockfish 17 ready"
          
      - name: Configure Bot
        run: |
          # Insert token into config
          sed -i "s/^token:.*/token: \"${LICHESS_TOKEN}\"/" config.yml
          
          # Verify config is valid YAML
          python -c "import yaml; yaml.safe_load(open('config.yml'))" && echo "✅ Config is valid"
          
      - name: Start Bot
        run: |
          echo "🚀 Starting Lichess bot at $(date)"
          echo "⏰ Bot will run for ~110 minutes before restart"
          
          timeout 6600s python -u user_interface.py -u 2>&1 | tee bot.log || {
            exit_code=$?
            echo "🛑 Bot stopped at $(date)"
            if [ $exit_code -eq 124 ]; then
              echo "✅ Timeout reached - normal 2-hour restart cycle"
              exit 0
            else
              echo "❌ Bot failed with exit code: $exit_code"
              exit $exit_code
            fi
          }
          
      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bot-logs-${{ github.run_number }}
          path: bot.log
          retention-days: 3
